/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a new message */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contact/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a list of all contact categories */
        get: operations["showAllCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of all registrations by year */
        get: operations["showAllRegistrations"];
        put?: never;
        /** Create a new registration for a specific year */
        post: operations["createRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration/{year}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meta info for the year */
        get: operations["showRegistraionYearMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registration/{year}/{id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delete a registration via link */
        get: operations["deleteRegistrationGet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remote-submissions/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a remote submission */
        post: operations["createRemoteSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remote-submissions/{year}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of active remote compos for a year */
        get: operations["listRemoteSubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Country: {
            /**
             * @description Country ISO 3166-1 alpha-2 code
             * @example FR
             */
            code: string;
            /**
             * @description Country name
             * @example France
             */
            name: string;
        };
        DeleteRegistrationGetOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DeleteRegistrationGetOutputBody.json
             */
            readonly $schema?: string;
            message: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        GetContactCategoriesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetContactCategoriesOutputBody.json
             */
            readonly $schema?: string;
            categories: components["schemas"]["GetContactCategoryItem"][] | null;
        };
        GetContactCategoryItem: {
            /**
             * @description ID of the contact category
             * @example website
             */
            id: string;
            /**
             * @description Title of the contact category
             * @example Website
             */
            title: string;
        };
        GetRegistrationItem: {
            /**
             * @description Country name of the registered user
             * @example France
             */
            country_name: string | null;
            /**
             * @description 5711 & Haujobb
             * @example Group of the registered user
             */
            group: string | null;
            /**
             * @description ID of the registered user
             * @example 5711
             */
            id: string;
            /**
             * @description Handle or name of the registered user
             * @example Hénry Chevale
             */
            name: string;
            /**
             * @description Website of the registered user
             * @example http://www.pouet.net/groups.php?which=5711
             */
            website_url: string | null;
        };
        GetRegistrationMetaOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetRegistrationMetaOutputBody.json
             */
            readonly $schema?: string;
            countries: components["schemas"]["Country"][] | null;
            /** @description Is the registation currently open? */
            is_open: boolean;
        };
        GetRegistrationsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetRegistrationsOutputBody.json
             */
            readonly $schema?: string;
            registrations: components["schemas"]["GetRegistrationItem"][] | null;
        };
        GetRemoteSubmissionItem: {
            /**
             * @description ID of the remote compo
             * @example 2027-pc-64k-intro
             */
            id: string;
            /**
             * @description Name of the remote compo
             * @example PC 64k Intro
             */
            name: string;
        };
        GetRemoteSubmissionsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GetRemoteSubmissionsOutputBody.json
             */
            readonly $schema?: string;
            remote_submissions: components["schemas"]["GetRemoteSubmissionItem"][] | null;
        };
        PostContactInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostContactInputBody.json
             */
            readonly $schema?: string;
            /** @description Captcha response to be verified server side */
            captcha_response: string;
            /**
             * @description ID of the contact category
             * @example website
             */
            category_id: string;
            /**
             * @description Email of the sender
             * @example hans@example.com
             */
            email: string;
            /**
             * @description Message by the sender (10-5000 characters)
             * @example Lorem ipsum...
             */
            message: string;
            /**
             * @description Name/Nickname of the sender (2-100 characters)
             * @example Hans
             */
            name: string;
            /**
             * @description Subject by the sender (at least 5 characters)
             * @example Congratulations
             */
            subject: string;
        };
        PostRegistrationsInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostRegistrationsInputBody.json
             */
            readonly $schema?: string;
            /** @description Captcha response to be verified server side */
            captcha_response: string;
            /**
             * @description ISO 3166-1 alpha-2 country code of the user (2 letters)
             * @example FR
             */
            country_code?: string;
            /**
             * @description Group of the user (at most 100 characters)
             * @example 5711 & Haujobb
             */
            group?: string;
            /**
             * @description Handle or name of the user (2-100 characters)
             * @example Hénry Chevale
             */
            name: string;
            /**
             * @description Website of the user (absolute http/https URL)
             * @example http://www.pouet.net/groups.php?which=5711
             */
            website_url?: string;
        };
        PostRegistrationsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostRegistrationsOutputBody.json
             */
            readonly $schema?: string;
            registration: components["schemas"]["GetRegistrationItem"];
        };
        PostRemoteSubmissionOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PostRemoteSubmissionOutputBody.json
             */
            readonly $schema?: string;
            submission: components["schemas"]["RemoteSubmissionResponse"];
        };
        RemoteSubmissionResponse: {
            artist_first_name: string;
            artist_group: string | null;
            artist_handle: string;
            artist_last_name: string;
            /** Format: date-time */
            created_at: string;
            email: string;
            id: string;
            remote_compo_id: string;
            remote_compo_name: string;
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostContactInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    showAllCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetContactCategoriesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    showAllRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year to query for */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRegistrationsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year to register for */
                year: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostRegistrationsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRegistrationsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    showRegistraionYearMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year to get meta information for */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRegistrationMetaOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteRegistrationGet: {
        parameters: {
            query?: {
                /** @description Secret token to authorize deletion */
                token?: string;
            };
            header?: never;
            path: {
                /** @description Year of the edition */
                year: number;
                /** @description ID of the registration to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRegistrationGetOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createRemoteSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year of the event */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    address_city: string;
                    /**
                     * @description ISO 3166-1 alpha-2 country code
                     * @example DE
                     */
                    address_country: string;
                    address_street: string;
                    address_zip: string;
                    artist_first_name: string;
                    artist_group?: string;
                    artist_handle: string;
                    artist_last_name: string;
                    captcha_response: string;
                    email: string;
                    /** Format: binary */
                    file: string;
                    message_organizers?: string;
                    message_visitors?: string;
                    remote_compo_id: string;
                    title: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRemoteSubmissionOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listRemoteSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Year to query for */
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetRemoteSubmissionsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
